### ISSUE TITLE
300版本bios下触控板可否正常工作？

### ISSUE THREAD

**Issue by ghost** [originman521/Hackintosh-ASUS-FXPRO-GL552VW#1]
不知道什么原因，我的bios无法更新，会卡在更新页面，无论使用winflash或者easyflash，我看到说明页写着触控板可以在304版本下工作，请问300版本可以正常使用吗？或者我可以怎么修改配置文件使其工作？

**Comment by originman521** [comment]
抱歉 比较忙不怎么上github 我的bios版本是最新的304  旧的bios不能够用触摸板

**Comment by originman521** [comment]
更新bios即可
