### ISSUE TITLE
为什么我用你的EFI选择u盘启动后系统不能进入clover？

### ISSUE THREAD

**Issue by q944093** [originman521/Hackintosh-ASUS-FXPRO-GL552VW#2]
还是每次都进入windows boot manager并且报错。已经关闭了安全模式

**Comment by q944093** [comment]
问题解决了，我认为你给的boot下bootx64.efi文件是win10的引导文件。把clover里的x64.efi重命名替换掉boot文件夹里的那个就可以引导了。

**Comment by originman521** [comment]
是的 替换bootx64
